import = [
	"~/.config/alacritty/themes/themes/one_dark.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[window]
padding = { x = 6, y = 6 }
opacity = 0.97
