---
- name: Install alacritty requirements
  become: true
  ansible.builtin.apt:
    pkg:
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - python3
      - libxkbcommon-dev 

- name: Download Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust

- name: Update stable rust
  ansible.builtin.command: rustup update stable

- name: Clone alacritty
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty.git"
    dest: '~/Git/alacritty'

- name: Make alacritty
  ansible.builtin.command: cargo build --release
  args:
    chdir: ~/Git/alacritty

- name: Setup alacritty
  ansible.builtin.command: sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
  args:
    chdir: ~/Git/alacritty

- name: Add shell completitions
  block: 
    - name: create alacritty completition folder
      ansible.builtin.command: mkdir -p ${ZDOTDIR:-~}/.zsh_functions
      args:
        chdir: ~/Git/alacritty

    - name: create alacritty completition folder
      ansible.builtin.command: echo 'fpath+=${ZDOTDIR:-~}/.zsh_functions' >> ${ZDOTDIR:-~}/.zshrc
      args:
        chdir: ~/Git/alacritty

    - name: copy completion to file history
      ansible.builtin.command: cp extra/completions/_alacritty ${ZDOTDIR:-~}/.zsh_functions/_alacritty
      args:
        chdir: ~/Git/alacritty

- name: Copy alacritty config to config folder
  ansible.builtin.copy:
    src: ../config/alacritty/
    dest: ~/.config/alacritty/
    remote_src: true
    force: true
