# Shell variables
# Generated by 'wal'
wallpaper='/home/lucas/git/Dotfiles/wallpapers/walls/MistyTrees.jpg'

# Special
background='#090F17'
foreground='#dee1e9'
cursor='#dee1e9'

# Colors
color0='#090F17'
color1='#718BA8'
color2='#8B9FBA'
color3='#A5B5CC'
color4='#B9C6D6'
color5='#BACBE1'
color6='#C3CCDD'
color7='#dee1e9'
color8='#9b9da3'
color9='#718BA8'
color10='#8B9FBA'
color11='#A5B5CC'
color12='#B9C6D6'
color13='#BACBE1'
color14='#C3CCDD'
color15='#dee1e9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
