---
- name: Install nvim deps
  become: true
  ansible.builtin.apt:
    pkg:
      - gettext
      - lua5.4
      - liblua5.4-dev
      - ninja-build

- name: Clone nvim repo
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: '~/Git/nvim'
    version: stable

- name: Make install nvim
  ansible.builtin.command: sudo make install
  args:
    chdir: '~/Git/nvim'

- name: Copy nvim config to config folder
  ansible.builtin.copy:
    src: ../config/nvim/
    dest: ~/.config/nvim
    remote_src: true
    force: true
