---
- name: Tmux - create .tmux folder
  ansible.builtin.file:
    path: ~/.tmux/
    state: directory 

- name: Tmux - install via apt
  ansible.builtin.apt:
    name: tmux
    state: present

- name: Tmux - clone tpm
  ansible.builtin.git:
    name: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: copy tmux config
  ansible.builtin.copy:
    src: ../config/tmux/tmux.conf
    dest: $HOME/.tmux.conf

- name: copy tmux keymaps
  ansible.builtin.copy:
    src: ../config/tmux/tmux.keymaps.conf
    dest: $HOME/.tmux.keymaps.conf
