---
- name: Install packages
  become: yes
  ansible.builtin.apt:
    pkg:
      - git
      - build-essential
      - curl
      - fzf
      - cmake

- name: Create git folder
  ansible.builtin.file:
    path: '~/Git'
    state: directory

